parameters:
#    tixi_app_driver_vacation.example.class: Tixi\App\DriverVacationBundle\Example

services:
#    tixi_app_driver_vacation.example:
#        class: %tixi_app_driver_vacation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
