parameters:
#    tixi_app_driver_recurring_task.example.class: Tixi\App\DriverRecurringTaskBundle\Example

services:
#    tixi_app_driver_recurring_task.example:
#        class: %tixi_app_driver_recurring_task.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
