parameters:
#    tixi_app_driver_details.example.class: Tixi\App\DriverDetailsBundle\Example

services:
#    tixi_app_driver_details.example:
#        class: %tixi_app_driver_details.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
