parameters:
#    tixi_app_driver_schedule.example.class: Tixi\App\DriverScheduleBundle\Example

services:
#    tixi_app_driver_schedule.example:
#        class: %tixi_app_driver_schedule.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
