parameters:
#    tixi_app_holiday.example.class: Tixi\App\HolidayBundle\Example

services:
#    tixi_app_holiday.example:
#        class: %tixi_app_holiday.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
