language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION="2.3.*" DB=mysql
  - SYMFONY_VERSION="2.4.*" DB=mysql
  - SYMFONY_VERSION="dev-master" DB=mysql

before_script:
  - yes | cp app/config/parameters.yml app/config/parameters.yml.bak
  - composer install -n
  - composer require symfony/http-foundation:${SYMFONY_VERSION}

script: 
  - phpunit --coverage-text
  - yes | cp app/config/parameters.yml.bak app/config/parameters.yml
  
notifications:
  email:
    - hertus@gmail.com