language: php

php:
  - 5.5

before_script:
  - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml

script: phpunit -c app