language: php

php:
  - 5.5

env:
  - SYMFONY_VERSION="2.3.*" DB=mysql

before_script:
  - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:update --force

script: phpunit -c app