parameters:
#    tixi_app_passenger_data.example.class: Tixi\App\PassengerDataBundle\Example

services:
#    tixi_app_passenger_data.example:
#        class: %tixi_app_passenger_data.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
