tixi_login:
    pattern:  /login
    defaults: { _controller: TixiSecurityBundle:Security:login }

tixi_login_check:
    pattern:  /login_check

tixi_logout:
    pattern:  /logout

tixi_oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: TixiSecurityBundle:Security:login }

tixi_oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: TixiSecurityBundle:Security:loginCheck }
