parameters:
#    tixi_security.example.class: Tixi\SecurityBundle\Example

services:
#    tixi_security.example:
#        class: %tixi_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
