imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: tixi.yml }
    - { resource: "@FOSOAuthServerBundle/Resources/config/security.xml" }

framework:
    translator:      { fallback: de_DE }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  de_DE
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    globals:
      tixi_parameter_app: %tixi_parameter_app%
      tixi_parameter_version: %tixi_parameter_version%
      tixi_parameter_client: %tixi_parameter_client%
      tixi_parameter_client_page: %tixi_parameter_client_page%

    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    form:
        resources:
            - 'TixiApiBundle:Form:fieldsBootstrap.html.twig'


# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
      types:
        utcdatetime: Tixi\CoreDomainBundle\Types\UTCDateTimeTypeDoctrine
      default_connection: tixi
      connections:
        tixi:
          driver:   "%database_driver%"
          host:     "%database_host%"
          port:     "%database_port%"
          dbname:   "%database_name%"
          user:     "%database_user%"
          password: "%database_password%"
          charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:
          default:
            connection: tixi
            mappings:
              TixiSecurityBundle: ~
              CoreDomain:
                is_bundle: false
                type: annotation
                alias: Model
                prefix: Tixi\CoreDomain\
                dir: "%kernel.root_dir%/../src/Tixi/CoreDomain"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:
      type: memory
#      if you set spool type to file, you have to trigger the send process (by cron job for example)
#      path: %kernel.root_dir%/spool/mail

# Bundles Configuration
fos_rest:
    param_fetcher_listener: true
    format_listener: true
    routing_loader:
        default_format: html
    view:
        force_redirects:
            html: true

apy_breadcrumb_trail:
    template: ::breadcrumbTrail.html.twig

fos_oauth_server:
    db_driver:           orm     # Driver availables: orm, mongodb, or propel
    client_class:        Tixi\SecurityBundle\Entity\Client
    access_token_class:  Tixi\SecurityBundle\Entity\AccessToken
    refresh_token_class: Tixi\SecurityBundle\Entity\RefreshToken
    auth_code_class:     Tixi\SecurityBundle\Entity\AuthCode
    service:
        user_provider:   tixi_user_provider
        options:
            supported_scopes: user

monolog:
  handlers:
    main:
      type:   stream
      path:   %kernel.root_dir%/logs/main_%kernel.environment%.log
      level:  error
    doctrine:
      type:   stream
      path:   %kernel.root_dir%/logs/doctrine_%kernel.environment%.log
      level:  error
      channels: doctrine
    entity:
      type:   stream
      path:   %kernel.root_dir%/logs/entity.log
      level:  info
      channels: entity_channel

knp_snappy:
    pdf:
        enabled:    true
        binary:     %wkhtmltopdf_path%
        options:    []
    image:
        enabled:    false