
# redirecting the root
root:
    path: /
    defaults:
        _controller: TixiApiBundle:Home:getHome
        path: /home
        permanent: true

tixi_api:
    resource: "@TixiApiBundle/Controller/"
    type:     annotation
    prefix:   /

tixi_core_domain:
    resource: "@TixiCoreDomainBundle/Controller/"
    type:     annotation
    prefix:   /

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

tixi_security:
    resource: "@TixiSecurityBundle/Resources/config/routing.yml"
    prefix:   /
