tixi_app_mysql_dump:
    resource: "@TixiAppMysqlDumpBundle/Resources/config/routing.yml"
    prefix:   /

tixi_app_vehicle_serviceplan:
    resource: "@TixiAppVehicleServiceplanBundle/Resources/config/routing.yml"
    prefix:   /

tixi_app_vehicle_details:
    resource: "@TixiAppVehicleDetailsBundle/Resources/config/routing.yml"
    prefix:   /

tixi_app_vehicle_data:
    resource: "@TixiAppVehicleDataBundle/Resources/config/routing.yml"
    prefix:   /

tixi_app_team:
    resource: "@TixiAppTeamBundle/Resources/config/routing.yml"
    prefix:   /

tixi_app_preferences:
    resource: "@TixiAppPreferencesBundle/Resources/config/routing.yml"
    prefix:   /

tixi_security:
    resource: "@TixiSecurityBundle/Resources/config/routing.yml"
    prefix:   /

tixi_pub_customer:
    resource: "@TixiPubCustomerBundle/Resources/config/routing.yml"
    prefix:   /

tixi_pub_logout:
    resource: "@TixiPubLogoutBundle/Resources/config/routing.yml"
    prefix:   /

tixi_pub_support:
    resource: "@TixiPubSupportBundle/Resources/config/routing.yml"
    prefix:   /

tixi_pub_help:
    resource: "@TixiPubHelpBundle/Resources/config/routing.yml"
    prefix:   /

tixi_pub_about:
    resource: "@TixiPubAboutBundle/Resources/config/routing.yml"
    prefix:   /

tixi_home:
    resource: "@TixiHomeBundle/Resources/config/routing.yml"
    prefix:   /

