tixi_pub_support:
    resource: "@TixiPubSupportBundle/Resources/config/routing.yml"
    prefix:   /

tixi_pub_help:
    resource: "@TixiPubHelpBundle/Resources/config/routing.yml"
    prefix:   /

tixi_pub_about:
    resource: "@TixiPubAboutBundle/Resources/config/routing.yml"
    prefix:   /

tixi_home:
    resource: "@TixiHomeBundle/Resources/config/routing.yml"
    prefix:   /

