# 26.08.2013 martin jonasse initial file, credit the book - chapter 13 - security
#                           reference: security.yml.dist is the original file
# 27.08.2013 martin jonasse set access control to /app (needs login credentials)
# 28.08.2013 martin jonasse set all links to lowercase

security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path: tixi_login
                check_path: login_check
                default_target_path: tixi_home_page


    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /app, roles: [ROLE_USER, ROLE_ADMIN] }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [main, in_memory]
        main:
            id: tixi_user_provider
        in_memory:
            memory:
                users:
                    admin@btb.ch: { password: admin, roles: ['ROLE_USER', 'ROLE_ADMIN'] }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Tixi\UserBundle\Service\MyUser: plaintext

