# 26.08.2013 martin jonasse initial file, credit the book - chapter 13 - security
#                           reference: security.yml.dist is the original file
# 27.08.2013 martin jonasse set access control to /app (needs login credentials)
# 28.08.2013 martin jonasse set all links to lowercase

security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: tixi_home_page


    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /app, roles: [ROLE_USER, ROLE_ADMIN] }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    josi@btb.ch:  { password: josi, roles: ['ROLE_USER', 'ROLE_ADMIN'] }
                    josi@tixizug.ch:  { password: josi, roles: ['ROLE_USER', 'ROLE_ADMIN'] }
                    martin@btb.ch: { password: martin, roles: ['ROLE_USER', 'ROLE_ADMIN'] }
                    martin@tixizug.ch: { password: martin, roles: ['ROLE_USER', 'ROLE_ADMIN'] }
                    carmelo@btb.ch: { password: carmelo, roles: ['ROLE_USER', 'ROLE_ADMIN'] }
                    carmelo@tixizug.ch: { password: carmelo, roles: ['ROLE_USER', 'ROLE_ADMIN'] }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

