parameters:
     tixi_parameter_app: iTIXI
     tixi_parameter_version: v2.0.2.8
     tixi_parameter_client: TIXIZUG
     tixi_parameter_client_page: http://www.tixizug.ch

     tixi_parameter_google_apikey: AIzaSyAj6w00ufayAcAv-A8zzLhQspEYflknr4E
     tixi_parameter_osrm_server: http://seiout.ch:8080