parameters:
     tixi_parameter_app: iTIXI
     tixi_parameter_version: v2.0.3.2
     tixi_parameter_client: TIXIZUG
     tixi_parameter_client_page: http://www.tixizug.ch

     tixi_parameter_files_directory: %kernel.root_dir%/cache/files
     tixi_parameter_admin_mail: itixizug@gmail.com

     tixi_parameter_google_apikey: AIzaSyAj6w00ufayAcAv-A8zzLhQspEYflknr4E
     tixi_parameter_osrm_server: seiout.ch:8080
