#vehicle:
#  resource: Tixi\ApiBundle\Controller\VehicleController
#  type:     rest
vehicle:
  resource: Tixi\ApiBundle\Controller\VehicleController
  type:     annotation
  prefix:   /

#serviceplan:
#  resource: Tixi\ApiBundle\Controller\ServicePlanController
#  type:     rest
#  parent:   vehicle
serviceplan:
  resource: Tixi\ApiBundle\Controller\ServicePlanController
  type:     annotation
  prefix:   /

driver:
  resource: Tixi\ApiBundle\Controller\DriverController
  type:     annotation
  prefix:   /

passenger:
  resource: Tixi\ApiBundle\Controller\PassengerController
  type:     rest

home:
  resource: Tixi\ApiBundle\Controller\HomeController
  type:     annotation
  prefix:   /

