vehicle:
  resource: Tixi\ApiBundle\Controller\VehicleController
  type:     rest

serviceplan:
  resource: Tixi\ApiBundle\Controller\ServicePlanController
  type:     rest
  parent:   vehicle

driver:
  resource: Tixi\ApiBundle\Controller\DriverController
  type:     rest

passenger:
  resource: Tixi\ApiBundle\Controller\PassengerController
  type:     rest