parameters:
#    tixi_app_driver_data.example.class: Tixi\App\DriverDataBundle\Example

services:
#    tixi_app_driver_data.example:
#        class: %tixi_app_driver_data.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
