parameters:
#    tixi_app_shift.example.class: Tixi\App\ShiftBundle\Example

services:
#    tixi_app_shift.example:
#        class: %tixi_app_shift.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
