parameters:
#    tixi_pub_about.example.class: Tixi\Pub\AboutBundle\Example

services:
#    tixi_pub_about.example:
#        class: %tixi_pub_about.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
