parameters:
#    tixi_user.example.class: Tixi\UserBundle\Example

services:
    tixi_user_provider:
        class: Tixi\UserBundle\Service\UserProvider

    tixi_user_data:
        class: Tixi\UserBundle\Controller\UserData
        arguments: [@service_container]

#    tixi_user.example:
#        class: %tixi_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
