parameters:
#    tixi_user.example.class: Tixi\UserBundle\Example

services:
    tixi_user_provider:
        class: Tixi\UserBundle\Service\UserProvider
#    tixi_user.example:
#        class: %tixi_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
