parameters:
#    tixi_app_driver_agenda.example.class: Tixi\App\DriverAgendaBundle\Example

services:
#    tixi_app_driver_agenda.example:
#        class: %tixi_app_driver_agenda.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
