parameters:
#    tixi_app_vehicle_serviceplan.example.class: Tixi\App\VehicleServiceplanBundle\Example

services:
#    tixi_app_vehicle_serviceplan.example:
#        class: %tixi_app_vehicle_serviceplan.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
