# 26.08.2013 martin jonasse initial file
# 27.08.2013 martin jonasse added @service_container
# 08.10.2013 martin jonasse renamed service from tixi_homepage_service to tixi_housekeeper
# 08.19.2013 martin jonasse added services statebuilder and formbuilder

parameters:
#    tixi_home.example.class: Tixi\HomeBundle\Example

services:
    tixi_housekeeper:
        class: Tixi\HomeBundle\Controller\HouseKeeper
        arguments: [@service_container]
    tixi_formstatebuilder:
        class: Tixi\HomeBundle\Controller\FormStateBuilder
        arguments: [@service_container]
    tixi_listbuilder:
        class: Tixi\HomeBundle\Controller\ListBuilder
        arguments: [@service_container]
    tixi_autoform:
        class: Tixi\HomeBundle\Controller\AutoForm
        arguments: [@service_container]
    tixi_dataminer:
        class: Tixi\HomeBundle\Controller\DataMiner
        arguments: [@service_container]
#
#   stackoverflow "How to use Namespaced Sessions in Symfony2"
#    session:
#        class: Symfony\Component\HttpFoundation\Session\Session
#        arguments:
#            - @session.storage
#            - @tixi.session.attribute_bag
#            - @session.flash_bag
#    tixi.session.attribute_bag:
#        class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag

#    tixi_home.example:
#        class: %tixi_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
