parameters:
#    tixi_home.example.class: Tixi\HomeBundle\Example

services:
    tixi_homepage_service:
        class: Tixi\HomeBundle\Controller\HomepageController
        arguments: [HomepageController]
#    tixi_home.example:
#        class: %tixi_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
