# 26.08.2013 martin jonasse initial file
# 27.08.2013 martin jonasse added @service_container
# 23.09.2013 martin jonasse renamed service from tixi_homepage_service to tixi_housekeeping

parameters:
#    tixi_home.example.class: Tixi\HomeBundle\Example

services:
    tixi_housekeeping:
        class: Tixi\HomeBundle\Controller\HomepageController
        arguments: [@service_container]
    tixi_listbuilder:
        class: Tixi\HomeBundle\Controller\ListBuilder
        arguments: [@service_container]

#    tixi_home.example:
#        class: %tixi_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
