parameters:
#    tixi_home.example.class: Tixi\HomeBundle\Example

services:
#    tixi_home.example:
#        class: %tixi_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
