parameters:
#    tixi_app_zoneplan.example.class: Tixi\App\ZoneplanBundle\Example

services:
#    tixi_app_zoneplan.example:
#        class: %tixi_app_zoneplan.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
