parameters:
#    tixi_app_vehicle_data.example.class: Tixi\App\VehicleDataBundle\Example

services:
#    tixi_app_vehicle_data.example:
#        class: %tixi_app_vehicle_data.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
