parameters:
#    tixi_pub_logout.example.class: Tixi\Pub\LogoutBundle\Example

services:
#    tixi_pub_logout.example:
#        class: %tixi_pub_logout.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
